set_property IOSTANDARD TMDS_33 [get_ports HDMI_D2_P_0]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D1_P_0]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_D0_P_0]
set_property IOSTANDARD TMDS_33 [get_ports HDMI_CLK_P_0]
set_property PACKAGE_PIN L19 [get_ports HDMI_D0_P_0]
set_property PACKAGE_PIN M19 [get_ports HDMI_D1_P_0]
set_property PACKAGE_PIN K19 [get_ports HDMI_D2_P_0]
set_property PACKAGE_PIN K17 [get_ports HDMI_CLK_P_0]

set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN T11 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN T10 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN V13 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN U13 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PACKAGE_PIN R14 [get_ports IIC_0_0_scl_io]
set_property PACKAGE_PIN P14 [get_ports IIC_0_0_sda_io]

#set_property IOSTANDARD LVCMOS33 [get_ports {KEY_BORD_COL[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {KEY_BORD_COL[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {KEY_BORD_COL[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {KEY_BORD_COL[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {KEY_BORD_ROW[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {KEY_BORD_ROW[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {KEY_BORD_ROW[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {KEY_BORD_ROW[0]}]
#set_property PACKAGE_PIN V7 [get_ports {KEY_BORD_ROW[3]}]
#set_property PACKAGE_PIN U7 [get_ports {KEY_BORD_ROW[2]}]
#set_property PACKAGE_PIN W6 [get_ports {KEY_BORD_ROW[1]}]
#set_property PACKAGE_PIN V6 [get_ports {KEY_BORD_ROW[0]}]
#set_property PACKAGE_PIN Y9 [get_ports {KEY_BORD_COL[3]}]
#set_property PACKAGE_PIN Y8 [get_ports {KEY_BORD_COL[2]}]
#set_property PACKAGE_PIN V8 [get_ports {KEY_BORD_COL[1]}]
#set_property PACKAGE_PIN W8 [get_ports {KEY_BORD_COL[0]}]

#set_property PULLDOWN true [get_ports {KEY_BORD_COL[3]}]
#set_property PULLDOWN true [get_ports {KEY_BORD_COL[2]}]
#set_property PULLDOWN true [get_ports {KEY_BORD_COL[1]}]
#set_property PULLDOWN true [get_ports {KEY_BORD_COL[0]}]
#set_property PULLDOWN true [get_ports {KEY_BORD_ROW[3]}]
#set_property PULLDOWN true [get_ports {KEY_BORD_ROW[2]}]
#set_property PULLDOWN true [get_ports {KEY_BORD_ROW[1]}]
#set_property PULLDOWN true [get_ports {KEY_BORD_ROW[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Port_0_adc_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Port_0_adc_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Port_0_adc_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Port_0_adc_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Port_0_adc_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Port_0_adc_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Port_0_adc_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Port_0_adc_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_Port_0_adc_clk]
set_property PACKAGE_PIN Y17 [get_ports ADC_Port_0_adc_clk]
set_property PACKAGE_PIN T17 [get_ports {ADC_Port_0_adc_data[7]}]
set_property PACKAGE_PIN W18 [get_ports {ADC_Port_0_adc_data[6]}]
set_property PACKAGE_PIN R18 [get_ports {ADC_Port_0_adc_data[5]}]
set_property PACKAGE_PIN R16 [get_ports {ADC_Port_0_adc_data[3]}]
set_property PACKAGE_PIN R17 [get_ports {ADC_Port_0_adc_data[1]}]
set_property PACKAGE_PIN V18 [get_ports {ADC_Port_0_adc_data[0]}]
set_property PACKAGE_PIN V17 [get_ports {ADC_Port_0_adc_data[2]}]
set_property PACKAGE_PIN W19 [get_ports {ADC_Port_0_adc_data[4]}]
set_property SLEW FAST [get_ports ADC_Port_0_adc_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {DAC_Port_0_dac_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_Port_0_dac_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_Port_0_dac_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_Port_0_dac_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_Port_0_dac_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_Port_0_dac_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_Port_0_dac_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_Port_0_dac_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports DAC_Port_0_clk]
set_property SLEW FAST [get_ports DAC_Port_0_clk]
set_property SLEW FAST [get_ports {DAC_Port_0_dac_data[7]}]
set_property SLEW FAST [get_ports {DAC_Port_0_dac_data[6]}]
set_property SLEW FAST [get_ports {DAC_Port_0_dac_data[5]}]
set_property SLEW FAST [get_ports {DAC_Port_0_dac_data[4]}]
set_property SLEW FAST [get_ports {DAC_Port_0_dac_data[3]}]
set_property SLEW FAST [get_ports {DAC_Port_0_dac_data[2]}]
set_property SLEW FAST [get_ports {DAC_Port_0_dac_data[1]}]
set_property SLEW FAST [get_ports {DAC_Port_0_dac_data[0]}]
set_property PACKAGE_PIN W15 [get_ports DAC_Port_0_clk]
set_property PACKAGE_PIN T15 [get_ports {DAC_Port_0_dac_data[7]}]
set_property PACKAGE_PIN T14 [get_ports {DAC_Port_0_dac_data[5]}]
set_property PACKAGE_PIN U17 [get_ports {DAC_Port_0_dac_data[0]}]
set_property PACKAGE_PIN P15 [get_ports {DAC_Port_0_dac_data[1]}]
set_property PACKAGE_PIN V16 [get_ports {DAC_Port_0_dac_data[2]}]
set_property PACKAGE_PIN P16 [get_ports {DAC_Port_0_dac_data[3]}]
set_property PACKAGE_PIN W16 [get_ports {DAC_Port_0_dac_data[4]}]
set_property PACKAGE_PIN V15 [get_ports {DAC_Port_0_dac_data[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {In2_0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_1_0_sda_io]
set_property PACKAGE_PIN H15 [get_ports IIC_1_0_sda_io]
set_property PACKAGE_PIN G15 [get_ports IIC_1_0_scl_io]

set_property PACKAGE_PIN T19 [get_ports {In2_0[0]}]

set_disable_timing {get_cells design_1_i/ADDA/AXI4_IO_0/inst/AXI4_IO_v1_0_S00_AXI_inst/_reg*_reg[*]}
set_false_path -from [get_pins {design_1_i/ADDA/AXI4_IO_0/inst/AXI4_IO_v1_0_S00_AXI_inst/_reg1_reg[*]/C}] -to [get_pins {design_1_i/ADDA/AXI4Stream_2_DAC_0/inst/data_reg[*]/D}]
set_false_path -from [get_pins {design_1_i/ADDA/AXI4_IO_0/inst/AXI4_IO_v1_0_S00_AXI_inst/_reg2_reg[0]/C}] -to [get_pins design_1_i/ADDA/AXI4_Stream_Switch_0/inst/switch_reg_reg/D]

set_property DRIVE 12 [get_ports IIC_1_0_scl_io]
set_property DRIVE 12 [get_ports IIC_1_0_sda_io]
